services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: infrashop
      POSTGRES_USER: infrashop
      POSTGRES_PASSWORD: supersecret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - infranet

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://infrashop:supersecret@db:5432/infrashop
      JWT_SECRET: replace-me
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - infranet

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - infranet

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/infrashop.conf:/etc/nginx/conf.d/default.conf:ro
      # mount certs later
    depends_on:
      - frontend
      - backend
    networks:
      - infranet

volumes:
  db-data:

networks:
  infranet:
